$(document).ready(function(){
    $(".espace").click(function(){
    	$(".pRessource").hide();
    	$(".pExercice").hide();
    	$(".pEspace").show();
		$(".pAjoutAdmin").hide();
		$(".pAjoutSentiment").hide();
		$(".pAjoutBesoin").hide();
		$(".pAjoutExercice").hide();
		$(".pAjoutQuestion").hide();
		$(".pDeleteSentiment").hide();
		$(".pDeleteBesoin").hide();
		$(".pDeleteExercice").hide();
		$(".pDeleteQuestion").hide();
		$(".pLogin").hide();
		$(".pSign").hide();
		$(".pAffiche").hide();
		$("#logoAccueil").hide();
        $("#accueil").hide();
        $("#description").hide();
        $("#menuHorizontal").hide();
    	console.log("test");
    }); 
})
